#!/bin/sh
# backflip 
# Start my personal wmutils settings.

shoutout &
sxhkd -c ~/bin/backflip.sxhkd -f 90 -r ~/var/log/sxhkd.log ~/bin/launch.sxhkd &
platform &

wew | while IFS=: read ev wid; do
case $ev in
    # Window focusing
    7) 
    focus $wid
    ;;

    # occurs on mapped windows
    16) 
   
    routine $wid
    chwb -s 1 $wid

    ;;
    esac
done
