#!/bin/sh

__ScriptVersion="0.1"

#===  FUNCTION  ================================================================
#         NAME:  usage
#  DESCRIPTION:  Display usage information.
#===============================================================================
function usage ()
{
    echo "Usage :  $0 [options] [--] <disp>

    Options:
    -h|help       Display this message
    -u|unit       Run unit tests
    -v|version    Display script version
    "
    

}    # ----------  end of function usage  ----------

#-----------------------------------------------------------------------
#  Handle command line arguments
#-----------------------------------------------------------------------

while getopts ":hvu" opt
do
  case $opt in

    h|help     )  usage; exit 0   ;;
    u|unit     )  exit $(unit);; 
    v|version  )  echo "$ -- Version $__ScriptVersion"; exit 0   ;;

    * )  echo -e "\n  Option does not exist : $OPTARG\n"
          usage; exit 1   ;;

  esac    # --- end of case ---
done
shift $(($OPTIND-1))

mid () {
    disp=$(wim -a $(wmp))
}

function utest() {
    test ls

}

