#!/bin/sh
# Routine: what does something do when it gets opened?

# Default operation: center it on the mouse pointer. 
class=$(wclass -c $1)

function default() {
    #move to he 
    wmv -a $(wmp) "$1"
    chwb -s 1 -c $(tcolor "color8" | sed 's/#/0x/') $1
}

if ! wattr o $1 ; then
    case $class in
        weechat) groups -s $1 2; default $1 ;;
        ncmpcpp) groups -s $1 5; default $1 ;;
        mutt) groups -s $1 5; default $1 ;;
        Telegram) groups -s $1 2; default $1 ;;
        dmenu) ;;
        9menu) ;;
        * ) default $1 ;;
    esac
fi
